import { Image } from "@chakra-ui/image";
import { Input } from "@chakra-ui/input";
import { HStack, ListItem, OrderedList, Text, VStack } from "@chakra-ui/layout";
import {
  Modal,
  ModalCloseButton,
  ModalHeader,
  ModalOverlay,
  ModalBody,
  ModalContent,
  ModalFooter,
} from "@chakra-ui/modal";
import {
  Box,
  Button,
  FormControl,
  FormLabel,
  useClipboard,
  Flex,
} from "@chakra-ui/react";
import { useDispatch } from "react-redux";
import { Icon } from "@chakra-ui/icon";
import { closeModal } from "../../store/slices/ModalSlice";
import { useAuth } from "../../context/AuthContext";
import { useEffect } from "react";
import { useForm, FormProvider } from "react-hook-form";
import { CopyInput } from "../CopyInput";

const TwoFactorAuthModal = ({ isOpen }) => {
  const dispatch = useDispatch();
  const { twoFactorData, twoFaAuthenticaiton, verifyTowFa } = useAuth();
  const methods = useForm({
    mode: "onBlur",
  });
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = methods;
  useEffect(() => {
    twoFaAuthenticaiton();
  }, []);
  const onSubmit = (data) => {
    verifyTowFa(data?.verifyCode);
  };
  return (
    <Modal
      size={"3xl"}
      isOpen={isOpen}
      onClose={() => dispatch(closeModal())}
    >
      <ModalOverlay backdropFilter="blur(10px)" />
      <FormProvider {...methods}>
        <form action="" onSubmit={handleSubmit(onSubmit)}>
          <ModalContent
            bg={"#241446"}
            borderRadius={"24px"}
            border={"1px solid"}
            borderColor={"#3B2864"}
            p={"25px"}
            className={"ModalCentered"}
          >
            <ModalHeader
              mb={"20px"}
              p={0}
              className={"Archivo"}
              fontSize={"24px"}
              fontWeight={"bold"}
            >
              2FA Activation
            </ModalHeader>
            <ModalCloseButton
              fontSize={"15px"}
              mt={2}
              _focus={{ boxShadow: "none" }}
              color={"#ada7b7"}
            />
            <ModalBody>
              <box
                mb={"0px"}
                p={0}
                className={"Archivo"}
                fontSize={"18px"}
                fontWeight={"normal"}
              >
                Complete your 2FA activation process as mentioned below.
              </box>
              <box bg={"#140533"}></box>
              <VStack position="relative">
                <HStack
                  justifyContent="space-around"
                  alignItems="start"
                  w="100%"
                  bg="#140533"
                  border={"solid 1px"}
                  borderColor={"#3B2864"}
                  borderRadius={"6px"}
                  padding={"32px"}
                  marginTop={"10px"}
                >
                  <Box w={"60%"}>
                    <HStack justifyContent="center">
                      <Image w="200px" src={twoFactorData?.qrCodeUrl} />
                    </HStack>
                    <Text
                      textAlign="center"
                      variant="subtitleLabel"
                      color="#777777"
                      marginTop={"10px"}
                    >
                      Authenticator Secret Code
                    </Text>
                  </Box>

                  <Box w={{ xl: "100%", lg: "100%" }} margin={"10px, 80px"}>
                    <OrderedList
                      spacing={6}
                      fontSize={"16px"}
                      fontWeight={"normal"}
                    >
                      <ListItem>Open your Google Authenticator App</ListItem>
                      <ListItem>Scan the QR code</ListItem>
                      <ListItem>
                        To add an account manually copy and paste the text code
                        Below into the app
                      </ListItem>
                      <CopyInput
                        copyText={twoFactorData?.secret}
                        copyValue={twoFactorData?.secret}
                      />
                      <ListItem>
                        Enter the code generated by the app below
                      </ListItem>
                    </OrderedList>
                    <FormControl mb={"24px"} mt={"24px"}>
                      <Input
                        marginLeft={"19px"}
                        width={"95%"}
                        placeholder=""
                        formControlProps={{ width: "20%" }}
                        _placeholder={{ opacity: 1, color: "#5C498E" }}
                        type="text"
                        name="verifyCode"
                        {...register("verifyCode")}
                      />
                    </FormControl>
                  </Box>
                </HStack>
                <VStack spacing={10}></VStack>
                <VStack spacing={4} justifyContent="center" alignItems="center">
                  {/* <Text variant="subtitleLabel">
                ENTER THE CODE GIVEN BY THE GOOGLE AUTHENTICATOR APP
              </Text> */}
                </VStack>
              </VStack>
            </ModalBody>
            <ModalFooter>
              <Button
                colorScheme="blue"
                mr={3}
                onClick={() => dispatch(closeModal())}
              >
                Close
              </Button>
              <Button type="submit" variant="solid">
                SAVE CHANGES
              </Button>
            </ModalFooter>
          </ModalContent>
        </form>
      </FormProvider>
    </Modal>
  );
};

export default TwoFactorAuthModal;
