export const endpoints = {
  LOGIN: "/auth/login",
  SIGNUP: "/auth/signup",
  LOGOUT: "/users/logout",
  RESENT_VERIFY_EMAIL: "/auth/resend-email",
  GOOGLE_AUTH: "/auth/google-login",
  FACEBOOK_AUTH: "/auth/facebook-login",
  EMAIL_VERIFICAION: "/auth/verify-email",
  FORGOT_PASSWORD: "/auth/forgot-password-email",
  RESET_PASSWORD: "/auth/update-password",
  RESET_LINK_EXPIRY: "/auth/token-expiry",
  PROFILE: "/users/profile",
  PASS_KEY: "/auth/passkey",
  PASS_KEY_VERIFICATION: "/auth/passkey/register-verify",
  PASS_KEY_AUTHENTICATION: "/auth/passkey/login",
  ENABLE_TWO_FACTOR_AUTH: "/2fa/setup",
  DISABLE_TWO_FACTOR_AUTH: "/2fa/disable",
  VERIFY_TWO_FACTOR_AUTH: "/2fa/verify",
  VALIDATE_TWO_FACTOR_AUTH: "/auth/validate2FA",
  PROFILE_PHOTO: "/users/profile-photo",
  TOKENS: "/tokens",
  DEFAULT_TOKENS: "/tokens/default-tokens",
  TOKENS_DETAIL: "/erc20/token",
  ADD_TOKEN: "/tokens/add",
  CREAT_TOKEN: "/tokens/create",
  CONTACT_BOOK: "/users/contact-books",
  NOTIFICATION: "/notifications",
  GENERATE_PASSKEY: "/users/passkey-register-info",
  VERIFY_PASSKEY: "/users/verify-passkey-register-info",
  AUTHENTICATE_PASSKEY: "/auth/passkey/generate-option",
  VERIFY_AUTH_PASSKEY: "/auth/passkey/verify-auth-options",
  DELETE_PASSKEY: "/users/passkey",
  TOKEN_ADDRESS_INFO: "/tokens/info",
  NFTS: "/nfts/get-tokens-by-wallet-address",
  NFT_DETAIL: "/nfts/details",
  NFT_TRANSFER_HISTORY: "/nfts/transfers",
};
export const messages = {
  confirmation_modal: {
    title: "Are you sure",
    message: "Do you want to disable 2FA?",
    actionLabel: "YES",
    cancelLabel: "NO",
  },
};
export const CURRENCY_SYMBOL = "LAVA";
