import { useState } from "react";
import {
  Box,
  Flex,
  Heading,
  Text,
  Button,
  SimpleGrid,
  Image,
  GridItem,
  InputLeftElement,
  InputGroup,
  FormControl,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  Icon,
} from "@chakra-ui/react";
import Web3 from "web3";
import { useBreakpointValue } from "@chakra-ui/react";
import Header from "../../components/Header";
import Siderbar from "../../components/Siderbar";
import Head from "next/head";
import ProfileBar from "../../components/ProfileBar";

import BgGradient from "../../public/gradient-bg.png";
import { useWeb3React } from "@web3-react/core";
import { injected } from "../../utils/connector";

export default function Wallet() {
  const {
    active,
    account,
    library,
    connector,
    activate,
    deactivate,
    injectedWeb3React,
    chainId,
  } = useWeb3React();

  async function connect() {
    try {
      await activate(injected).then(async () => {
        if (typeof window.ethereum === "undefined") {
          return;
        }
        if (window.ethereum.networkVersion !== 1339) {
          try {
            await window.ethereum.request({
              method: "wallet_switchEthereumChain",
              params: [{ chainId: Web3.utils.toHex(1339) }],
            });
          } catch (e) {
            AddNetwork();
          }
          Cookies.set("isWalletConnected", true);
          localStorage.setItem("isWalletConnected", true);
        }
      });
      return true;
    } catch (ex) {
      console.log(ex);
    }
  }

  async function disconnect() {
    try {
      deactivate();
      Cookies.remove("isWalletConnected");
      localStorage.setItem("isWalletConnected", false);
    } catch (ex) {
      console.log(ex);
    }
  }
  const AddNetwork = async () => {
    await window.ethereum.request({
      method: "wallet_addEthereumChain",
      params: [
        {
          chainId: "0x53B",
          chainName: "Elysium",
          nativeCurrency: { name: "LAVA", symbol: "LAVA", decimals: 18 },
          rpcUrls: [process.env.NEXT_PUBLIC_RPC_URL],
          blockExplorerUrls: ["https://explorer.elysiumchain.tech/"],
        },
      ],
    });
  };

  return (
    <>
      {/* <Head>
                  <title>Wallet</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
              </Head> */}
      <Box flex="1">
        <Box mb={"52px"}>
          <Heading mb={"20px"} as={"h3"} size={"md"}>
            Wallet {account}
          </Heading>
          <SimpleGrid columns={2} spacing={"20px"}>
            <Box
              onClick={() => {
                connect();
              }}
              as={"button"}
              textAlign={"center"}
              position={"relative"}
              _hover={{ opacity: "0.98" }}
              _before={{
                content: '""',
                position: "absolute",
                top: `0`,
                left: `0`,
                height: `100%`,
                width: `100%`,
                display: "block",
                borderRadius: "16px",
                zIndex: "-1",
                backgroundImage: `${BgGradient.src}`,
                backgroundSize: "100% 100%",
                backgroundRepeat: "no-repeat",
                mixBlendMode: "color-dodge",
              }}
              fontFamily={"Archivo"}
              fontWeight={"600"}
              fontSize={"24px"}
              color={"#fff"}
              p={"50px 25px"}
              borderRadius={"16px"}
              border={"solid 1px"}
              borderColor={"rgba(255,255,255,0.1)"}
            >
              <Icon
                xmlns="http://www.w3.org/2000/svg"
                mb={"20px"}
                width="64px"
                height="64px"
                viewBox="0 0 64 64"
              >
                <g transform="translate(0.125 0.125)">
                  <path
                    d="M43.068,1,19.824,18.5,24.147,8.187Z"
                    transform="translate(13.489 -1)"
                    fill="#e17726"
                    stroke="#e17726"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M2.663,1,25.7,18.663,21.584,8.187Z"
                    transform="translate(0.28 -1)"
                    fill="#e27625"
                    stroke="#e27625"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M30.919,23.533l-6.184,9.613,13.243,3.71,3.794-13.113Z"
                    transform="translate(17.269 17.043)"
                    fill="#e27625"
                    stroke="#e27625"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M1.273,23.744l3.77,13.113,13.22-3.71L12.1,23.533Z"
                    transform="translate(-0.79 17.043)"
                    fill="#e27625"
                    stroke="#e27625"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M12.07,18.115,8.392,23.762l13.1.607-.437-14.35Z"
                    transform="translate(4.69 6.221)"
                    fill="#e27625"
                    stroke="#e27625"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M29.25,18.188l-9.127-8.26-.3,14.513,13.1-.607Z"
                    transform="translate(13.489 6.149)"
                    fill="#e27625"
                    stroke="#e27625"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M10.873,33.012l7.932-3.9L11.977,23.7Z"
                    transform="translate(6.6 17.178)"
                    fill="#e27625"
                    stroke="#e27625"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M20.266,29.115l7.909,3.9L27.094,23.7Z"
                    transform="translate(13.829 17.178)"
                    fill="#e27625"
                    stroke="#e27625"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M28.175,30.6l-7.909-3.9.644,5.227-.069,2.217Z"
                    transform="translate(13.829 19.585)"
                    fill="#d5bfb2"
                    stroke="#d5bfb2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M10.873,30.6l7.357,3.547-.046-2.217.621-5.227Z"
                    transform="translate(6.6 19.585)"
                    fill="#d5bfb2"
                    stroke="#d5bfb2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M17.968,23.621l-6.575-1.96,4.644-2.17Z"
                    transform="translate(6.999 13.806)"
                    fill="#233447"
                    stroke="#233447"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M20.513,23.621l1.931-4.13,4.667,2.17Z"
                    transform="translate(14.019 13.806)"
                    fill="#233447"
                    stroke="#233447"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M13.553,33.147l1.15-9.613-7.311.21Z"
                    transform="translate(3.92 17.043)"
                    fill="#cc6228"
                    stroke="#cc6228"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M24.1,23.533l1.127,9.613,6.184-9.4Z"
                    transform="translate(16.779 17.043)"
                    fill="#cc6228"
                    stroke="#cc6228"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M32.929,17.651l-13.1.607,1.218,6.837,1.931-4.13,4.667,2.17Z"
                    transform="translate(13.489 12.332)"
                    fill="#cc6228"
                    stroke="#cc6228"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M13.7,23.134l4.644-2.17,1.931,4.13L21.5,18.257l-13.1-.607Z"
                    transform="translate(4.69 12.332)"
                    fill="#cc6228"
                    stroke="#cc6228"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M8.392,17.651l5.495,10.9L13.7,23.134Z"
                    transform="translate(4.69 12.332)"
                    fill="#e27525"
                    stroke="#e27525"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M24.331,23.134l-.207,5.413,5.495-10.9Z"
                    transform="translate(16.799 12.332)"
                    fill="#e27525"
                    stroke="#e27525"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M16.327,17.988l-1.219,6.837,1.54,8.073.345-10.64Z"
                    transform="translate(9.86 12.602)"
                    fill="#e27525"
                    stroke="#e27525"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M20.1,17.988l-.644,4.247L19.782,32.9l1.54-8.073Z"
                    transform="translate(13.209 12.602)"
                    fill="#e27525"
                    stroke="#e27525"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M21.183,22.656l-1.54,8.073,1.1.793,6.828-5.413.207-5.413Z"
                    transform="translate(13.349 14.771)"
                    fill="#f5841f"
                    stroke="#f5841f"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M11.393,20.7l.184,5.413L18.4,31.522l1.1-.793-1.54-8.073Z"
                    transform="translate(6.999 14.771)"
                    fill="#f5841f"
                    stroke="#f5841f"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M28.07,32.419l.069-2.217-.6-.513H18.759l-.575.513.046,2.217-7.357-3.547,2.575,2.147,5.219,3.663H27.61l5.242-3.663L35.4,28.872Z"
                    transform="translate(6.6 21.318)"
                    fill="#c0ac9d"
                    stroke="#c0ac9d"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M24.316,27.061l-1.1-.793H16.729l-1.1.793L15,32.288l.575-.513h8.782l.6.513Z"
                    transform="translate(9.78 19.232)"
                    fill="#161616"
                    stroke="#161616"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M43.716,19.643l1.954-9.66L42.728,1,20.266,17.917l8.644,7.42,12.208,3.617,2.69-3.2-1.172-.863L44.5,23.167l-1.425-1.12L44.935,20.6Z"
                    transform="translate(13.829 -1)"
                    fill="#763e1a"
                    stroke="#763e1a"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M1,9.983l1.977,9.66L1.713,20.6,3.6,22.047l-1.425,1.12,1.862,1.727-1.173.863,2.69,3.2L17.76,25.337l8.644-7.42L3.943,1Z"
                    transform="translate(-1 -1)"
                    fill="#763e1a"
                    stroke="#763e1a"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M38.149,18.131,25.941,14.515l3.679,5.647-5.495,10.9,7.265-.093H42.241Z"
                    transform="translate(16.799 9.822)"
                    fill="#f5841f"
                    stroke="#f5841f"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M17.55,14.515,5.342,18.131,1.273,30.965H12.1l7.265.093-5.495-10.9Z"
                    transform="translate(-0.79 9.822)"
                    fill="#f5841f"
                    stroke="#f5841f"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                  <path
                    d="M24.8,28.394l.782-13.673,3.54-9.73H13.354l3.541,9.73.782,13.673.3,4.293L18,43.3h6.483L24.5,32.688Z"
                    transform="translate(8.51 2.196)"
                    fill="#f5841f"
                    stroke="#f5841f"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="0.25"
                  />
                </g>
              </Icon>
              <Text display={"block"}>Connect MetaMask</Text>
            </Box>
            <Box
              as={"button"}
              textAlign={"center"}
              position={"relative"}
              _hover={{ opacity: "0.98" }}
              _before={{
                content: '""',
                position: "absolute",
                top: `0`,
                left: `0`,
                height: `100%`,
                width: `100%`,
                display: "block",
                borderRadius: "16px",
                zIndex: "-1",
                backgroundImage: `${BgGradient.src}`,
                backgroundSize: "100% 100%",
                backgroundRepeat: "no-repeat",
                mixBlendMode: "color-dodge",
              }}
              fontFamily={"Archivo"}
              fontWeight={"600"}
              fontSize={"24px"}
              color={"#fff"}
              p={"50px 25px"}
              borderRadius={"16px"}
              border={"solid 1px"}
              borderColor={"rgba(255,255,255,0.1)"}
            >
              <Icon
                xmlns="http://www.w3.org/2000/svg"
                mb={"20px"}
                width="56px"
                height="56px"
                viewBox="0 0 56 56"
              >
                <path
                  d="M3.417,52.582a11.665,11.665,0,0,1,0-16.5l13.2-13.2a11.665,11.665,0,0,1,16.5,0,2.333,2.333,0,1,1-3.3,3.3,7,7,0,0,0-9.9,0l-13.2,13.2a7,7,0,0,0,9.9,9.9l6.6-6.6a2.333,2.333,0,1,1,3.3,3.3l-6.6,6.6a11.663,11.663,0,0,1-16.5,0Zm18.15-18.149a2.333,2.333,0,0,1,3.3-3.3,7,7,0,0,0,9.9,0L49.283,16.614a7,7,0,0,0-9.9-9.9l-7.917,7.917a2.333,2.333,0,0,1-3.3-3.3l7.917-7.917a11.666,11.666,0,0,1,16.5,16.5L38.064,34.433a11.665,11.665,0,0,1-16.5,0Z"
                  transform="translate(0 0)"
                  fill="#fff"
                />
              </Icon>
              <Text display={"block"}>Create Wallet with MetaMask</Text>
            </Box>
          </SimpleGrid>
        </Box>
      </Box>
    </>
  );
}
